# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
  - checkout: self

  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
      versionSpec: 10.x
      checkLatest: true

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
      
  - task: Gulp@1
    displayName: 'Gulp Build'
    inputs:
      targets: build 
      
   - task: Gulp@0
     displayName: 'Bundle project'
     inputs:
      targets: bundle
      arguments: '--ship'

   
